Fixed async warning
dolezsa/thermal_comfort pull request #418
Opened 2024-12-08 15:51 UTC by Nicxe

A small contribution to dixed the async warning that will be deprecated

2024-12-27 18:25 UTC, z-master42 commented
Same as #417

2025-01-05 13:11 UTC, kroimon requested changes
Duplicate of #417.
Also includes unnecessary MacOS files (.DS_Store).

2025-01-05 13:46 UTC, Nicxe commented
Sorry, just tried to help to fix the issue, didn't we the other PR. Won't happen again

2025-01-05 13:46 UTC, closed without merging

2025-01-05 14:01 UTC, z-master42 commented
Help is always welcome.