Added Simmer Index and Simmer Zone sensors
dolezsa/thermal_comfort pull request #65
Opened 2022-01-06 21:16 UTC by ahmadtawakol

This is based on another fork of thermal_comfort by @lymanepp at https://github.com/lymanepp/thermal_comfort. I adapted the code to work with this plugin. The only thing missing is the translations for the Simmer Zone strings.

2022-01-07 01:47 UTC, lymanepp commented
Please give credit where it is due.

2022-01-07 08:37 UTC, rautesamtr requested changes
I'd suggest you squash the commits and add @lymanepp as Co-authored-by to give credit. Would that be ok for you @lymanepp?

2022-01-07 08:37 UTC, rautesamtr commented on README.md
> + * Simmer Zone `simmerzone`
Could you also add them to the list of available sensors for sensor_types?

2022-01-07 08:37 UTC, rautesamtr commented on custom_components/thermal_comfort/sensor.py
> +SIMMER_CIRCULATORY_COLLAPSE_IMMINENT = 'Circulatory collapse imminent'
Could you change those to short `snake_case` strings and add the proper string to sensor.en.json similar to the other translated strings?

2022-01-07 16:44 UTC, lymanepp commented
> I'd suggest you squash the commits and add @lymanepp as Co-authored-by to give credit. Would that be ok for you @lymanepp?

Yes, that sounds good to me.

2022-01-08 00:32 UTC, rautesamtr commented
@ahmadtawakol If your up for it, it would also be nice if you would add some test cases. Otherwise i can do it myself.

2022-01-10 18:20 UTC, closed without merging

2022-01-11 01:29 UTC, lymanepp commented
> > I'd suggest you squash the commits and add @lymanepp as Co-authored-by to give credit. Would that be ok for you @lymanepp?
> 
> Yes, that sounds good to me.

I don't see that any credit was given.

2022-01-11 01:32 UTC, ahmadtawakol commented
@lymanepp I closed this PR and created a new one. I added you as a co-author to the commit.

2022-01-11 01:33 UTC, lymanepp commented
> @lymanepp I closed this PR and created a new one. I added you as a co-author to the commit.

Thanks! 👍