Added Simmer Index and Simmer Zone
dolezsa/thermal_comfort pull request #67
Opened 2022-01-10 19:12 UTC by ahmadtawakol

Let's try this again! I messed up the [previous PR](https://github.com/dolezsa/thermal_comfort/pull/65) and thought it would be easier to create a new one.

This is based on another fork of thermal_comfort by @lymanepp at https://github.com/lymanepp/thermal_comfort. I adapted the code to work with this plugin. The only thing missing is the translations for the Simmer Zone strings.

2022-01-11 08:45 UTC, rautesamtr requested changes
Hey, thank you for your effort so far. I appreciate it. 

Since contributor documentation is still non existent, here some tipps.

You can use [pre-commit](https://pre-commit.com/) to run some checks before commiting.

To run the tests locally, run the following in a bash shell in the projects root directory:
```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements_test.txt
pytest
```

For the failing `assert len(hass.states.async_all(sensor.DOMAIN))` you could just fix the numbers, or add a constant eg `LEN_TEST_SENSORS = len(DEFAULT_SENSOR_TYPES) + 2` (Total default sensors + 2 command line input sensors) and use that for the checks with a coresponding offset where needed.

2022-01-11 08:45 UTC, rautesamtr commented on custom_components/thermal_comfort/sensor.py
> +
Theres some whitespace here when viewing the commit localy.

2022-01-11 08:45 UTC, rautesamtr commented on custom_components/thermal_comfort/sensor.py
> +            si = fahrenheit
Tests are broken since you did not consider this.

2022-01-11 10:44 UTC, rautesamtr commented on custom_components/thermal_comfort/sensor.py
> +
![image](https://user-images.githubusercontent.com/1131371/148928326-5028e3c0-a97c-49bf-810c-084fbf1b9d1c.png)

2022-01-11 22:47 UTC, ahmadtawakol commented
Sorry about that! I fixed the problems you pointed out. Let me know if there is anything else I missed or need to do!

2022-01-12 08:56 UTC, rautesamtr approved these changes
Looks good to me. Thank you!

2022-01-12 08:58 UTC, merged

2022-01-12 16:37 UTC, lymanepp commented
No credit will be given to the author?

2022-01-12 16:39 UTC, ahmadtawakol commented
@lymanepp You are mentioned in the release notes as well as a co-author on the commit in this PR.

2022-01-12 16:40 UTC, rautesamtr commented
![image](https://user-images.githubusercontent.com/1131371/149183173-77a79e0b-fd1d-452f-a7a6-c8c58d4c02de.png)
![image](https://user-images.githubusercontent.com/1131371/149183088-47fa7eb9-6a54-430f-af95-7ff42d833e8f.png)

2022-01-12 16:42 UTC, lymanepp commented
> @lymanepp You are mentioned in the release notes as well as a co-author on the commit in this PR.

I want a permanent mention in the README, not the PR or release notes that will soon be forgotten.

2022-01-12 16:49 UTC, rautesamtr commented
None of us has a permanent mention in the README. I explicitly askef if it was enough to be added as co author of the commit. If this is that important for you we can start a CONTRIBUTORS file and add you.

2022-01-12 16:51 UTC, lymanepp commented
> If this is that important for you we can start a CONTRIBUTORS file and add you.

That's a good idea!